# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'  # Specify the minimum iOS version

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'pkfiverr' do
  config = use_native_modules!
  use_modular_headers!
  
  $RNFirebaseAsStaticFramework = true
  use_frameworks! :linkage => :static

  
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'pkfiverrTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Ensure Xcode projects are correctly configured after installing pods
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # Uncomment if you want to enable ccache
      # :ccache_enabled => true
    )
    
    # Ensure static framework configuration
    installer.pods_project.targets.each do |target|
      if target.name.include?('gRPC-C++') || target.name.include?('gRPC-Core')
        target.build_configurations.each do |config|
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
      end
    end
  end
end
